baseURL       = "/"
languageCode  = "en-us"
title         = "ASSSA | Termiczna Obróbka Kruszyw"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Strona Główna"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "O nas"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Oferta"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Kontakt"
    url     = "contact"
    weight  = 4

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Imię"
    placeholder_last_name         = "Nazwisko"
    placeholder_email             = "Adres e-mail"
	placeholder_company           = "Firma"
    placeholder_about_the_project = "Treść wiadomości"
    send_message                  = "Wyślij wiadomość"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Kontakt"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/sand.jpg"
    heading               = "Termiczna Obróbka Kruszyw"
    tagline               = "ASSSA POLAND"
    primary_button        = "Sprawdź ofertę"
    primary_button_url    = "portfolio"
    secondary_button      = "Wyślij zapytanie"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OFERTA PRODUKTOWA"
    subtitle  = "Oferujemy kruszywa mineralne o standardowych granulacjach. Produkujemy również dowolne frakcje na życzenie klienta."
	subtitle2 = "Zapraszamy do kontaktu po szczegółową ofertę oraz wycenę zamówienia."
	
  
  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "ZŁÓŻ ZAMÓWIENIE"
    primary_button        = "Sprawdź ofertę"
    primary_button_url    = "portfolio"
    secondary_button      = "Wyślij zapytanie"
    secondary_button_url  = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Dane kontaktowe"
      address = "Glincz ul. Brzozowa 11<br>83-330 Żukowo, Polska"
	  nip     = "NIP 589-16-85-082"
      telfax  = "tel/fax: +48 (058) 681 73 24"
      email   = "info@roxo.co"
	  
	[params.footer.contactInfo2]
      title   = "Biuro"
      address = "Katarzyna Strawska"
      phone   = "+48 608 021 534"
      email   = "biuro@asssa.com.pl"
	  
	[params.footer.contactInfo3]
      title   = "Produkcja"
      address = "Waldemar Grzędzicki"
      phone   = "+48 600 033 629"
      email   = "produkcja@asssa.com.pl"

	  [params.footer.sitemap]
		title   = "Informacje"
		[[params.footer.sitemap.link]]
		  name = "O nas"
		  url  = "about"
		[[params.footer.sitemap.link]]
		  name = "Oferta"
		  url  = "portfolio"
		[[params.footer.sitemap.link]]
		  name = "Kontakt"
		  url  = "contact"
  