baseURL       = "http://as-production.github.io/"
languageCode  = "en-us"
title         = "AS | Termiczna Obróbka Kruszyw"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Strona Główna"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "O nas"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Produkty"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "del"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Kontakt"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Imię"
    placeholder_last_name         = "Nazwisko"
    placeholder_email             = "e-mail"
    placeholder_about_the_project = "Treść wiadomości"
    send_message                  = "Wyślij wiadomość"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Kontakt"
    url     = "contact"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/sand.jpg"
    heading               = "Termiczna Obróbka Kruszyw"
    tagline               = "AS PRODUCTION"
    primary_button        = "Sprawdź ofertę"
    primary_button_url    = "portfolio"
    secondary_button      = "Wyślij zapytanie"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Dane kontaktowe"
      address = "Glincz ul. Brzozowa 11<br>83-330 Żukowo, Polska"
	  address2= "NIP 589-16-85-082"
      phone   = "tel/fax: +48 (058) 681 73 24"
      email   = "info@roxo.co"
	  

		
		
		
		

	  
	  
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Nawigacja"
        [[params.footer.sitemap.link]]
          name = "O nas"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Produkty"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Kontakt"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help brands:"
        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"